from nltk.book import *
#fdist5 = FreqDist(texts)
#print(sorted([w for w in set(text5) if len(w) > 7 and fdist5[w] > 7]))
#print(text2[141525:])
#print(text4.collocations())
#print(text8.collocations())
#print([len(w) for w in text1])
fdist = FreqDist([len(w) for w in text1])
print(fdist)
#print(fdist.keys())
print(fdist.items())
print(fdist.max())
print(fdist[3])
print(fdist.freq(3))
print(fdist.plot(50, cumulative=True))